// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldhK6koWwi0JZ5waDNmohrt_NziZ1gGg',
    appId: '1:808680881975:web:e149472972935f549524b2',
    messagingSenderId: '808680881975',
    projectId: 'diario-visitas',
    authDomain: 'diario-visitas.firebaseapp.com',
    databaseURL: 'https://diario-visitas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diario-visitas.firebasestorage.app',
    measurementId: 'G-3XSNQ2MXJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiV9Fwq-tDsevRSDbQEVJ--l1L2cuimVI',
    appId: '1:808680881975:android:0c33d5d6e6b7e6aa9524b2',
    messagingSenderId: '808680881975',
    projectId: 'diario-visitas',
    databaseURL: 'https://diario-visitas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diario-visitas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDGxPnOuT1lRGxCvhn1rv6NdSzeiWQlQ',
    appId: '1:808680881975:ios:9ae0714c0bcba0119524b2',
    messagingSenderId: '808680881975',
    projectId: 'diario-visitas',
    databaseURL: 'https://diario-visitas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diario-visitas.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiarioVisitasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDGxPnOuT1lRGxCvhn1rv6NdSzeiWQlQ',
    appId: '1:808680881975:ios:9ae0714c0bcba0119524b2',
    messagingSenderId: '808680881975',
    projectId: 'diario-visitas',
    databaseURL: 'https://diario-visitas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diario-visitas.firebasestorage.app',
    iosBundleId: 'com.example.flutterDiarioVisitasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDldhK6koWwi0JZ5waDNmohrt_NziZ1gGg',
    appId: '1:808680881975:web:1481ae1a9f0caaa99524b2',
    messagingSenderId: '808680881975',
    projectId: 'diario-visitas',
    authDomain: 'diario-visitas.firebaseapp.com',
    databaseURL: 'https://diario-visitas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diario-visitas.firebasestorage.app',
    measurementId: 'G-CP2TFPTNNK',
  );
}
